# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-23 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='recommend_course',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
