# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-23 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191023_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '06.专题课'},
        ),
    ]
